Shrek:
  maxSubmit: 1000                    
  submissionPrefix: ../submit/
  defaultBranch: master
  # Soft limit (warning) on total size of resource files [kb]
  softResourceLimit: 400
  # Hard limit (error) on total size of resource files [kb]
  hardResourceLimit: 800

Donkey:
  period: 900
  scope: user.jwebb2
  match: "*"
  config: ".donkey"
  host: spmq01.sdcc.bnl.gov
  queue: /queue/events
  port: 61613

PanDA:
  vo: wlcg
  site: BNL_OSG_SPHENIX
  prodSourceLabel: test
  workingGroup: sphenix
  url:        https://sphenix-pandaserver.apps.rcf.bnl.gov/server/panda
  url_ssl:    https://sphenix-pandaserver.apps.rcf.bnl.gov/server/panda
  cache_url:  https://sphenix-pandaserver.apps.rcf.bnl.gov/server/panda
  mon_url:    https://sphenix-panda.apps.rcf.bnl.gov
  use_native_httplib: "1"
  behind_real_lb: "1"
  auth: oidc
  verify_host: "off"
  auth_vo: sphenix
  config_root: .pathena/
