Shrek:
  maxSubmit: 1000
  submissionPrefix: ../submit/
  defaultBranch: master

# ython -m stomp -H spmq01.sdcc.bnl.gov --user=donkey --password=donkey --listen=/queue/events
Donkey:
  period: 900
  scope: user.jwebb2
  match: "*"
  config: $HOME/.donkey
  host: spmq01.sdcc.bnl.gov
  queue: /queue/events
  port: 61613

PanDA:
  vo: wlcg
  site: BNL_OSG_SPHENIX
  prodSourceLabel: test
  workingGroup: sphenix
  url:     http://pandaserver-doma.cern.ch:25080/server/panda
  url_ssl: https://pandaserver-doma.cern.ch:25443/server/panda
  auth: oidc
  verify_host: "off"
  auth_vo: sphenix
  config_root: $HOME/.pathena
