Shrek:
  maxSubmit: 1000
  submissionPrefix: ../sPHENIX-test-production/
  defaultBranch: test

Donkey:
  period: 900
  scope: user.jwebb2
  match: "*"

PanDA:
  vo: wlcg
  site: BNL_OSG_SPHENIX
  prodSourceLabel: test
  workingGroup: sphenix

